DROP TABLE IF EXISTS j_role_j_user;
DROP TABLE IF EXISTS j_user;
DROP TABLE IF EXISTS j_role;

CREATE TABLE IF NOT EXISTS j_role (
    id SERIAL PRIMARY KEY,
    name VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS j_user (
    id SERIAL PRIMARY KEY,
    name VARCHAR(2000),
    role_id INT NOT NULL REFERENCES j_role(id)
);